In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from sklearn.preprocessing import QuantileTransformer, LabelEncoder

dataset = pd.read_csv("irrigation_data.csv")

In [3]:
dataset

    temp  humidity       weather  wind  label
0     26        88          Mist  2.60      1
1     25        70          Mist  2.50      1
2      1        98        Clouds  6.96      0
3     33        80        Clouds  4.00      0
4     10        60         Clear  4.10      0
5      2        30        Clouds  4.10      0
6     16        27          Rain  4.10      0
7     22       100          Rain  3.45      0
8     22        79          Rain  1.00      0
9     22        83          Rain  2.00      0
10    19        78          Rain  5.00      0
11    24        81          Rain  7.00      0
12    16        27          Rain  1.20      0
13    22        80          Rain  2.40      0
14    18        52         Clear  1.40      1
15    28        48         Clear  3.80      1
16    19        99  Thunderstorm  2.53      0
17    19        40       Drizzle  2.53      1
18    19        99  Thunderstorm  2.53      0
19    19        50       Drizzle  2.53      1
20    19        99       Drizzle  2.53      1

In [4]:
X = dataset.drop('label', axis=1)
y = dataset['label']

In [5]:
X

    temp  humidity       weather  wind
0     26        88          Mist  2.60
1     25        70          Mist  2.50
2      1        98        Clouds  6.96
3     33        80        Clouds  4.00
4     10        60         Clear  4.10
5      2        30        Clouds  4.10
6     16        27          Rain  4.10
7     22       100          Rain  3.45
8     22        79          Rain  1.00
9     22        83          Rain  2.00
10    19        78          Rain  5.00
11    24        81          Rain  7.00
12    16        27          Rain  1.20
13    22        80          Rain  2.40
14    18        52         Clear  1.40
15    28        48         Clear  3.80
16    19        99  Thunderstorm  2.53
17    19        40       Drizzle  2.53
18    19        99  Thunderstorm  2.53
19    19        50       Drizzle  2.53
20    19        99       Drizzle  2.53

In [6]:
y

0     1
1     1
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    1
15    1
16    0
17    1
18    0
19    1
20    1
Name: label, dtype: int64

In [7]:
le = LabelEncoder()

In [8]:
le.fit(X['weather'])

LabelEncoder()

In [9]:
X['weather'] = le.transform(X['weather'])

In [10]:
X

    temp  humidity  weather  wind
0     26        88        3  2.60
1     25        70        3  2.50
2      1        98        1  6.96
3     33        80        1  4.00
4     10        60        0  4.10
5      2        30        1  4.10
6     16        27        4  4.10
7     22       100        4  3.45
8     22        79        4  1.00
9     22        83        4  2.00
10    19        78        4  5.00
11    24        81        4  7.00
12    16        27        4  1.20
13    22        80        4  2.40
14    18        52        0  1.40
15    28        48        0  3.80
16    19        99        5  2.53
17    19        40        2  2.53
18    19        99        5  2.53
19    19        50        2  2.53
20    19        99        2  2.53

In [11]:
X['weather'] = le.transform(X['weather'])

/home/manh/.local/lib/python3.6/site-packages/numpy/lib/arraysetops.py:565: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)

ValueError: y contains previously unseen labels: [0, 1, 2, 3, 4, 5]

In [12]:
X

    temp  humidity  weather  wind
0     26        88        3  2.60
1     25        70        3  2.50
2      1        98        1  6.96
3     33        80        1  4.00
4     10        60        0  4.10
5      2        30        1  4.10
6     16        27        4  4.10
7     22       100        4  3.45
8     22        79        4  1.00
9     22        83        4  2.00
10    19        78        4  5.00
11    24        81        4  7.00
12    16        27        4  1.20
13    22        80        4  2.40
14    18        52        0  1.40
15    28        48        0  3.80
16    19        99        5  2.53
17    19        40        2  2.53
18    19        99        5  2.53
19    19        50        2  2.53
20    19        99        2  2.53

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [14]:
quantile_transformer = QuantileTransformer()
X_train = quantile_transformer.fit_transform(X_train)
X_test = quantile_transformer.transform(X_test)

In [15]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
classifier2 = classifier.fit(X_train, y_train)

In [16]:
classifier

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
y_pred

array([1, 0, 0, 1, 0])

In [19]:
acc = accuracy_score(y_test, y_pred)

In [20]:
acc

1.0

In [21]:
y_pred = classifier.predict(quantile_transformer.transform([[36,40,le.transform(["Clouds"])[0],1.1]]))

In [22]:
y_pred

array([1])

In [23]:
classifier.predict(X_test)

array([1, 0, 0, 1, 0])

In [24]:
classifier.predict([[36,40,1,2.6]])

array([0])

In [25]:
X_test

array([[3.66366366e-01, 1.03703704e-01, 4.00000000e-01, 3.66366366e-01],
       [2.00123200e-01, 9.99999998e-08, 7.66766767e-01, 3.33333333e-02],
       [3.66366366e-01, 9.33333333e-01, 9.99999900e-01, 3.66366366e-01],
       [3.66366366e-01, 9.33333333e-01, 4.00000000e-01, 3.66366366e-01],
       [3.66366366e-01, 4.59259259e-01, 7.66766767e-01, 8.87645688e-01]])

In [26]:
a = quantile_transformer.transform([[36,40,le.transform(["Clouds"])[0],1.1]])

In [27]:
a

array([[0.9999999 , 0.1037037 , 0.26676677, 0.01666667]])